# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: test

on: 
  push:
    branches:
      - 'main'
      - 'devops'

jobs:
  test-survey:
    runs-on: ubuntu-latest
    if: github.event == 'refs/heads/main'
    steps:
        - uses: actions/checkout@v3
        - name: Test
          run: echo 'this step is concerned by the main branch'
  test-model:
    runs-on: ubuntu-latest
    if: github.event == 'refs/heads/devops'
    steps:
        - uses: actions/checkout@v3
        - name: Test
          run: echo 'this step is concerned by the devops branch'