# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path


name: test

on: 
  push:
    branches:
      - 'main'
      - 'devops'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          ref: '${{ github.ref_name }}'
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Gather files changed
        uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b
        with:
          fileOutput: 'json'
          
      - name: Show files changed
        run: cat $HOME/files.json
      - name: command
        run: cd /home/runner/work/Java_app && ls 